src/components/basics/shared/site.js, src/components/layout/NpmDownloadCount.js, src/components/layout/NpmDownloadCount.stories.js, src/components/screens/CommunityScreen/CommunityHero.js, src/components/screens/IndexScreen/Hero.js
=> Get monthly installs from NPM

getContributorCount.js, package-lock.json, package.json, src/components/screens/CommunityScreen/CommunityHero.js
Raised to suggest an answer to issue https://github.com/storybooks/frontpage/issues/10
=> 10 get contributor count from GitHub

src/components/layout/NpmDownloadCount.js, src/components/layout/NpmDownloadCount.stories.js, src/components/screens/CommunityScreen/CommunityHero.js, src/components/screens/CommunityScreen/CommunityHero.stories.js, src/components/screens/CommunityScreen/CommunityScreen.js, src/components/screens/CommunityScreen/CommunityScreen.stories.js, src/components/screens/IndexScreen/Hero.js, src/components/screens/IndexScreen/Hero.stories.js, src/components/screens/IndexScreen/IndexScreen.js, src/components/screens/IndexScreen/IndexScreen.stories.js, src/components/screens/TeamScreen/TeamScreen.js, src/components/screens/TeamScreen/TeamScreen.stories.js, yarn.lock
This is the technique advocated by https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/testing-components-with-graphql.md
=> Refactored `StaticQuery` to top level of pages and leave out for stories.

src/components/basics/Video.js, src/components/basics/Video.stories.js, src/components/basics/index.js, src/components/layout/ValueProp.stories.js, src/components/screens/IndexScreen/Hero.js, src/components/screens/IndexScreen/IndexScreen.js
PR for https://github.com/storybooks/frontpage/issues/7
This introduces a `Video` component that can optionally change the src path to use a different video size, using the video files naming convention.
=> Introduction of a Video component to handle video performance

package.json, scripts/clone_and_build_docs.sh, static/_redirects
=> Add a script to clone and build the docs from the monorepo

gatsby-node.js, static/_redirects
Issue: #26 
- Redirect for the main docs page
=> Docs integration tweaks

src/components/screens/IndexScreen/IndexScreen.js
Very simple commit but without either the word 'your' or 'the' before UI
it didn't read as nicely
=> Edit wording of UX benefit to read better

.gitignore, src/components/screens/TeamScreen/TeamScreen.js
=> Just a small fix for my new work =)

src/components/screens/AddonScreen/AddonScreen.js, src/components/screens/IndexScreen/IndexScreen.js, src/components/screens/UseCasesScreen/UseCasesScreen.js
Minor tweaks. See commit messages for changelog.
=> Bugfixes and maintenance

gatsby-config.js
=> add display param to google font config

static/_redirects
Issue #31 
Restore /examples => /docs/examples redirect
=> Restore community examples page

package.json, site-metadata.js, src/components/layout/Header.js, src/components/lib/useSiteMetadata.js, src/components/screens/AddonScreen/AddonCustom.stories.js, src/components/screens/AddonScreen/AddonScreen.js, src/components/screens/CommunityScreen/CommunityScreen.js, src/components/screens/NotFoundScreen/NotFoundScreen.js, src/components/screens/SupportScreen/SupportScreen.js, src/components/screens/UseCasesScreen/UseCasesScreen.js, yarn.lock
This adds the Octocat image to the top-right corner of the page, linking to Storybook on GitHub. Similar to the docs site.
=> Add GitHub link to header

src/components/screens/AddonScreen/AddonScreen.js
Storybook AMP allow to render stories in AMP-HTML. (https://github.com/prototypearea/storybook-amp)
=> Add Community Addon / AMP

site-metadata.js, src/components/lib/useSiteMetadata.js, src/components/screens/AddonScreen/AddonScreen.js
=> Highlight SB docs on the addons page

src/components/screens/AddonScreen/AddonScreen.js
This adds `@whitespace/storybook-addon-html` to the list of community addons.
=> Add community addon HTML

src/components/screens/AddonScreen/AddonScreen.js
There's a plugin for Adobe XD that is similar to the Figma plugin. Adding it to the list in the docs.
=> Add the XD addon

src/components/screens/TeamScreen/Contributors.js, src/components/screens/TeamScreen/Contributors.stories.js, src/components/screens/TeamScreen/TeamItem.js, src/components/screens/TeamScreen/TeamList.js, src/components/screens/TeamScreen/TeamList.stories.js, src/components/screens/TeamScreen/TeamScreen.js
Draft changes to update TeamItem UI to look similar to the one attached in the #40.
@domyen So, I have created this draft PR to start working in #40 .
* In this I have updated the `TeamItem`, to look like the one you have attached in the issue description. 👍 .
Fell free to have a look in `netlify` preview generated, Let me know your thoughts in it, and I will update it accordingly.
=> TeamItem UI Updated.

src/components/screens/AddonScreen/AddonScreen.js
Add [Playroom](https://github.com/rbardini/storybook-addon-playroom) addon to the _Community addons_ section in addon screen.
=> Add Playroom addon to addon list

src/components/screens/AddonScreen/AddonScreen.js
Storybook Addon Preview can show user selected knobs in various framework code in Storybook
https://github.com/naver/storybook-addon-preview
https://naver.github.io/egjs-infinitegrid/storybook/
=> Add Code Preivew to addon list

src/components/screens/AddonScreen/AddonScreen.js
Storybook Addon - React Theming
Storybook addon for Styled Components, Emotion, Material-UI and any other theming solution
https://github.com/react-theming/storybook-addon
=> Add Addon to gallery

src/components/screens/AddonScreen/AddonScreen.js
I've been working on [this storybook addon](https://github.com/aholachek/storybook-mobile). It's quite new, hopefully it's ok to add it now -- if not I can retry this pr once it gets some users.
=> Add mention of storybook-mobile

src/components/screens/AddonScreen/AddonScreen.js
=> added dark mode addon 

gatsby-node.js, src/components/layout/Header.js, src/components/screens/ReleasesScreen/ReleasesScreen.js, src/content/releases/6.0.md
=> Prerelease notes for 6.0

gatsby-config.js, package.json, yarn.lock
We need to tell the server how to do redirects.
=> Add gatsby plugin netlify

.gitignore, gatsby-node.js, site-metadata.js, src/components/layout/Header.js, src/components/lib/useSiteMetadata.js, src/components/screens/DocsScreen/DocsScreen.tsx, src/components/screens/ReleasesScreen/ReleasesScreen.js
Super minimal rendering of the docs based on @kylesuss' work on rendering releases.
This is throwaway work but enough to get us moving.
=> Render docs

src/components/screens/IndexScreen/Hero.js
Storybook serves more than the Big Three™ now.
=> Minor fix in Subtitle

gatsby-config.js
Dup of #119, but targeting `master` this time because I didn't realize that the iframe stuff had already hit `master`.
=> Remove default Netlify headers

gatsby-config.js, package.json, site-metadata.js, src/components/lib/useSiteMetadata.js, src/components/screens/CommunityScreen/CommunityHero.js, src/components/screens/CommunityScreen/CommunityHero.stories.js, src/components/screens/CommunityScreen/CommunityScreen.js, src/components/screens/CommunityScreen/CommunityScreen.stories.js, src/components/screens/IndexScreen/Hero.js, src/components/screens/IndexScreen/Hero.stories.js, src/components/screens/IndexScreen/IndexScreen.js, src/components/screens/IndexScreen/IndexScreen.stories.js, src/components/screens/TeamScreen/TeamScreen.js, src/components/screens/TeamScreen/TeamScreen.stories.js
=> reinstated the contributor count

src/components/layout/DocsLayout.js, src/components/layout/DocsLayout.stories.js
To help w/ capturing styling & working in isolation.
=> Big dataset for TOC stories

site-metadata.js, src/components/lib/useSiteMetadata.js, src/components/screens/AddonScreen/AddonCustom.js, src/components/screens/AddonScreen/AddonScreen.js, src/components/screens/CommunityScreen/CommunityScreen.js, src/components/screens/IndexScreen/Hero.js, src/components/screens/IndexScreen/IndexScreen.js, src/components/screens/SupportScreen/SupportScreen.js
Fix homepage "get started" link as well as an assortment of other broken links caused by change in site metadata
=> Fix docs links

site-metadata.js, src/components/lib/useSiteMetadata.js, src/components/screens/AddonScreen/AddonScreen.js
=> Fix addons page

static/_redirects
Merge once this PR in Storybook is merged https://github.com/storybookjs/storybook/pull/11957
=> Update `_redirects` for example page

.storybook/main.js
In addition to the code here, I added the env var to Circle.
=>  Pass GATSBY_ALGOLIA_API_KEY to Storybook build

gatsby-node.js, src/components/layout/PageLayout.js, src/components/layout/PageLayout.stories.js, src/components/screens/ReleasesScreen/IframeReleasesScreen.js, src/components/screens/ReleasesScreen/Release.js
Fixes: https://github.com/storybookjs/storybook/issues/12193
=> Fix iframe layout, white background on iframe page, links opening in new window

src/components/screens/DocsScreen/DocsScreen.tsx
Closes #155 
Let's wait on https://github.com/storybookjs/storybook/pull/12545 to merge so that the frontpage builds ok.
=> Tell mobile Safari not to adjust small text

.gitignore, package.json, site-metadata.js, src/components/layout/Footer.js, src/components/layout/Header.js, src/components/screens/CommunityScreen/CommunityHero.js, src/components/screens/IndexScreen/Hero.js, yarn.lock
* Update DS dependency
* Use the new universal header from the SDS
* Move Github badge to header
* Add updated link for blog to header & footer
=> Header and Footer updates

gatsby-browser.js, gatsby-config.js, package.json, yarn.lock
Closes https://github.com/storybookjs/storybook/issues/13189
=> Dont load Segment on iframe pages

src/components/basics/SocialGraph.tsx, src/components/lib/useSiteMetadata.js
Tested using:
* https://metatags.io/
* https://cards-dev.twitter.com/validator
Fixes #199
=> Fix: twitter card metadata

package.json, src/components/basics/Breadcrumb.js, src/components/layout/DocsLayout.js, src/components/layout/addons/AddonItemDetail.js, src/components/layout/addons/AddonsLayout.js, yarn.lock
Related #205
Checkout Chromatic
=> Minor tweaks, UI updates, and design system update

src/components/screens/AddonsDetailScreen/AddonsDetailScreen.js, src/pages/addons.js, src/util/order-compatibility.js
Switch to the trending queries
Sort compatibility to display core frameworks first
=> Sorting compatibility and trending

src/components/screens/AddonsDetailScreen/AddonsDetailScreen.js
=> Fix readme table layout

src/hooks/use-addons-search.js
#205 
Tried to optimize the debouncing on the front-end. Previously it would wait a minimum of 150ms to even start searching. Now it starts instantly and then debounces.
=> minor optimization for addons search

site-metadata.js
https://discord.gg/storybook since we're an OSS project
=> Discord vanity URL

src/components/layout/Footer.js, src/components/layout/PageTitle.js
Merge when the LSB [PR merges](https://github.com/chromaui/learnstorybook.com/pull/437).
=> Update footer & tweak PageTitle

src/components/screens/AddonsCategoryScreen/AddonsCategoryScreen.js
=> Fix addons sidebar active state

site-metadata.js, src/content/releases/6.2.md, src/content/releases/6.3.md
- 6.2 release notes
- 6.3 placeholder notes
- upgrade latest version specifier
self-merging @domyen @winkerVSbecks
=> 6.2 release

site-metadata.js, src/components/screens/CommunityScreen/CommunityHero.js
Thanks for the reminder to update contributor count @nhoizey. It's even more now.
https://twitter.com/nhoizey/status/1388080424811905029
=> Update contributor count

src/components/screens/IndexScreen/Hero.js, src/components/screens/IndexScreen/IndexScreen.js
Grammar mistake in the Document section of the IndexScreen
=> IndexScreen: Fix grammar and minor tweak to spacing

site-metadata.js, src/content/releases/6.2.md, src/content/releases/6.3.md
Self-merging @domyen @winkerVSbecks
=> 6.3 release

src/components/screens/IndexScreen/IndexScreen.js
Grammar fix on the homepage.
| Before | After |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/2608321/135705108-4fb12e9d-e33a-4734-b78f-25e1ece96980.png) | ![image](https://user-images.githubusercontent.com/2608321/135705131-e78c3661-9b48-4fc4-962f-3f264b336fb9.png) |
=> fix (doc): remove incorrect article

src/components/screens/UseCasesScreen/UseCasesScreen.js
=> Fix create components carousel on use cases page

.github/workflows/push-all-release-branches.yml, docs/versioning.md
- Add manual trigger to `push-all-release-branches` workflow
- Update versioning docs
=> Add manual trigger to `push-all-release-branches` workflow

package.json, yarn.lock
Previously I've upgraded the design system to the prerelease version that 100% didn't have any visual changes (at least that was the intention of that prerelease version etc). Since then the v7 of the design system has been released and it can contain some visual changes (but it doesn't have to, I'm not sure) and it makes sense to just bring it up to date here now.
=> Upgrade to the very latest design system

src/hooks/use-addons-search.js
To test, go to `/addons` page and try searching for `msw`
=> allow 3 char search for addons

static/_redirects
Per changes in:
- https://github.com/storybookjs/storybook/pull/16425
- https://github.com/storybookjs/storybook/pull/17074
=> Update _redirects file

src/components/layout/addons/AddonItem.js
=> add a fallback for when addon doesn't have authors

src/components/layout/DocsLayout.js
- Restrict search to current version
- Same as we do for current framework
=> Restrict search to current version

src/components/screens/IndexScreen/IndexScreen.js
Found a typo and some bad links in the recent [homepage PR](https://github.com/storybookjs/frontpage/pull/335)
=> Fix typos and links

site-metadata.js, src/components/layout/Header.js, src/components/lib/useSiteMetadata.js
=> feat: rearrange nav links to add showcase

gatsby-config.js, gatsby-node.js, src/components/layout/DocsLayout.js, src/util/versions.js
- For use with Algolia DocSearch
- Pass version as `string` instead of `number` for DocSearch meta data
-----
The extant sitemap, used for search crawlers, for the path `/docs/react/get-started/introduction`, has this output:
```xml
<url> <loc>https://storybook.js.org/docs/react/get-started/introduction</loc> <changefreq>daily</changefreq> <priority>0.7</priority> </url>
```
The new `sitemap-all.xml`, for that same path, has this output which includes all versions and all frameworks:
```xml
<url> <loc>https://storybook.js.org/docs/react/get-started/introduction</loc> <changefreq>daily</changefreq> <priority>0.7</priority> </url>
<url> <loc>https://storybook.js.org/docs/6.3/react/get-started/introduction</loc> <changefreq>daily</changefreq> <priority>0.7</priority> </url>
<url> …
```
=> Generate sitemap-all.xml

src/components/layout/DocsLayout.js, src/components/layout/Footer.js, src/components/screens/DocsScreen/DocsScreen.tsx, src/components/screens/ReleasesScreen/Release.js, src/components/screens/ReleasesScreen/ReleasesScreen.js
=> Add semantic elements and classes to layout

package.json, src/components/screens/IndexScreen/Hero.js, src/components/screens/IndexScreen/IndexScreen.js, src/components/screens/IndexScreen/Integrations.stories.js, yarn.lock
- Fix BlogCTA on narrow screens
- Upgrade `@storybook/design-system`
=> Fix BlogCTA on narrow screens

src/util/redirects-raw.txt, static/_redirects
With this pull request, the redirects are updated for the builders documentation pull request that was recently introduced.
=> Chore: Adds redirects for builders 

docs/versioning.md
Updates for more accuracy and clarity
You can compare a rich diff here: https://github.com/storybookjs/frontpage/pull/366/files?short_path=c1cc304#diff-c1cc304e56dd03cbb5cf65c32d83c9b7ab069800b2ce780249ac87d320e76789
=> Update versioning docs [skip actions]

gatsby-node.js
Now points to `get-started/introduction` instead of the first TOC item
```diff
- /docs /docs/react/why-storybook 301
+ /docs /docs/react/get-started/introduction 301
- /docs/react /docs/react/why-storybook 301
+ /docs/react /docs/react/get-started/introduction 301
- /docs/vue /docs/vue/why-storybook 301
+ /docs/vue /docs/vue/get-started/introduction 301
- /docs/angular /docs/angular/why-storybook 301
+ /docs/angular /docs/angular/get-started/introduction 301
- /docs/web-components /docs/web-components/why-storybook 301
+ /docs/web-components /docs/web-components/get-started/introduction 301
- /docs/ember /docs/ember/why-storybook 301
+ /docs/ember /docs/ember/get-started/introduction 301
- /docs/html /docs/html/why-storybook 301
+ /docs/html /docs/html/get-started/introduction 301
- …
```
=> Update docs intro redirect

.github/workflows/push-all-release-branches.yml, README.md, netlify.toml, src/functions/versions.js
Picking up from @jmhobbs's PR https://github.com/storybookjs/frontpage/pull/406#issue-1431716800 and fixing our Github workflow
=> Add security headers and fix github workflow

scripts/extract-monorepo-version.sh
- Change package.json path for v7.0 onwards to code/package.json
=> Fix release pages generation

site-metadata.js, src/components/screens/IntegrationsCatalog/IntegrationsCatalogHomeScreen/IntegrationsCatalogHomeScreen.js, src/components/screens/IntegrationsCatalog/IntegrationsCategoryScreen/IntegrationsCategoryScreen.js, src/components/screens/IntegrationsCatalog/IntegrationsTagScreen/IntegrationsTagScreen.js, src/components/screens/IntegrationsCatalog/RecipesDetailScreen/RecipesDetailScreen.js
Sibling PR to https://github.com/storybookjs/storybook/pull/20108
=> Update integrations docs

site-metadata.js, src/components/screens/IntegrationsCatalog/AddonsDetailScreen/AddonsDetailScreen.js, src/components/screens/IntegrationsCatalog/IntegrationsCatalogHomeScreen/IntegrationsCatalogHomeScreen.js, src/components/screens/IntegrationsCatalog/IntegrationsCategoryScreen/IntegrationsCategoryScreen.js, src/components/screens/IntegrationsCatalog/IntegrationsTagScreen/IntegrationsTagScreen.js, src/components/screens/IntegrationsCatalog/RecipesDetailScreen/RecipesDetailScreen.js, src/util/redirects-raw.txt, static/_redirects
Fix what I missed in #439 
(Sorry @kylegach)
Also includes updates due to https://github.com/storybookjs/storybook/pull/20186
=> Redirect to new integrations docs

src/components/screens/DocsScreen/DocsScreen.tsx, src/util/relative-to-root-links.js
Refactor `relativeToRootLinks` to optionally include a version
=> Add LinkWithVersion to MDX components

src/util/redirects-raw.txt
=> Add redirect for `/docs/api/mdx`

static/_redirects
Initial work to get the status page going! Accessible only via URL, for now.
=> Add status page to _redirects

src/util/relative-to-root-links.js
- Previously, only added version to hrefs like `../path/to/page`
- Now also adds version to hrefs like `./page`
=> Fix LinkWithVersion

src/content/recipes/@sveltejs/kit.md
=> Add SvelteKit recipe

src/components/layout/DocsLayout.js
=> Add survey CTA to docs sidebar

src/content/recipes/tailwindcss.md
Fix for https://github.com/storybookjs/addon-styling/issues/13
=> Fix code snippets for data attribute decorator

src/content/recipes/@emotion/styled.md, src/content/recipes/@mui/material.md, src/content/recipes/@sveltejs/kit.md, src/content/recipes/bootstrap.md, src/content/recipes/next.md, src/content/recipes/sass.md, src/content/recipes/styled-components.md, src/content/recipes/tailwindcss.md, src/content/recipes/vuetify.md
- Update all recipes to use storybook's new init command
- Update recipe assumptions for Storybook 7.0
- Remove references to MDX stories
=> Update recipes for Storybook 7.0

src/content/recipes/less.md, src/util/create-integrations-pages/create-recipe-details-pages.js
=> Add LESS recipe

src/pages/docs.tsx
- To trigger a Chromatic build that should have no changes
=> Add comment

src/functions/docs-feedback.js
- Discussion body only contains cumulative rating
- All other feedback in comments
See #535
=> Revise feedback format

src/util/redirects-raw.txt
- Corresponds with https://github.com/storybookjs/storybook/pull/22970
=> Add redirect from /docs/api/argtypes to /docs/api/arg-types

src/content/recipes/@mui/material.md
Closes #594
- Updated snippet for including mui types in docs
=> Recipes: Update docgen config snippet for material UI 

src/util/redirects-raw.txt
- See: https://github.com/storybookjs/storybook/pull/24925/commits/d18e1a6fa009afa1005bc0be6d6452a9e0ba917d#diff-6ecdbfd9b39f5fa559024e372f9979981f52ad1911ed53d6e1db4997c3b7c9cc
=> Update redirects to match changes in monorepo

src/components/basics/CodeSnippets/BaseCodeSnippet/SnippetEyebrows/SnippetEybrows.tsx, src/components/basics/CodeSnippets/SyntaxHighlighterContext.tsx, src/components/basics/InPageTOC.tsx, src/components/layout/DocsLayout/Sidebar.tsx, src/components/screens/DocsScreen/DocsScreen.tsx, src/styles/formatting.js
- Configure shiki with all necessary languages
- Improve Sidebar and "On this page" styles
- Consistent link styles for both
- Block-level links
- Slightly darker gray color
- Blue, no underline on hover
- Show "On this page" if there is at least one heading
- Append ` • Storybook docs` to document title
- Fix broken `scroll-margin-top`
- Improve snippet eyebrow styles
=> QA feedback, round 1

src/content/releases/7.6.md, src/content/releases/8.0.md
> [!WARNING]
> Currently blocked on https://github.com/storybookjs/storybook/pull/25020
=> Add 8.0 pre-release

src/content/releases/7.6.md
I wrote the wrong changelog for 7.6.md 🤦
=> Fix 7.6.md content

gatsby-config.js, package.json, patches/gatsby-plugin-plausible+0.0.7.patch, src/util/custom-events.ts, static/_redirects, yarn.lock
=> Add Plausible analytics to Frontpage

scripts/append-package-tags-in-snippets.js, scripts/append-package-tags-in-snippets.test.ts
- Append for `add` command
- Add package disallow list
=> Update package tags script

package.json, yarn.lock
We tried and are now discontinuing these notion docs.
=> Remove conf and jobs board from the header & footer

package.json, src/components/screens/IndexScreen/IndexScreen.js, src/components/screens/IndexScreen/IndexScreen.stories.jsx, yarn.lock
In this PR I'm fixing a bug with overlapping on mobile creating an horizontal scroll. I'm also updating the Github link in the header to point to Github instead.
=> Homepage fixes for mobile

netlify.toml, src/content/releases/8.0.md
- Update 8.0 release
- Remove preRelease: true
- Update CSP
- Accept any sub-domain for Google domains
=> Misc fixes

package.json, src/components/screens/IndexScreen/Hero.js, src/components/screens/IndexScreen/SocialValidation.js, yarn.lock
This PR fixes these issues:
- Spacing on social cards
- Replace Twitter logo in the footer
- Fix newsletter button in the footer
- Fix some alignment in the hero section
=> Fixes on the new homepage post launch

package.json, yarn.lock
We are trying to bring components-marketing back to see if the deployment problems comes from there.
=> Try bringing back components-marketing

src/components/screens/IntegrationsCatalog/IntegrationsCatalogHomeScreen/IntegrationsCatalogHomeScreen.js, src/components/screens/IntegrationsCatalog/IntegrationsCatalogHomeScreen/IntegrationsCatalogHomeScreen.stories.js, src/util/create-integrations-pages/create-integrations-home-page.js
=> Add VTA callout to integrations catalog homepage

static/_redirects
- Replace with temporary redirect to useful GH issue
=> Remove status page redirect

package.json, yarn.lock
See: https://github.com/storybookjs/components-marketing/pull/81
=> Upgrade components-marketing
