- package.json
- src/components/tooltip/Popper.stories.js
- src/components/tooltip/Tooltip.js
- src/components/tooltip/Tooltip.stories.js
- src/components/tooltip/WithTooltip.js
- src/components/tooltip/WithTooltip.stories.js
- yarn.lock
@domyen since we wrote the `WithTooltip` component (which uses popper directly), this library has appeared: https://www.npmjs.com/package/react-popper-tooltip
The library handles the low-level tooltip stuff like `trigger` (what we called `mode`, i.e. `click` vs `hover` etc).
It ships with some styles, but not the styles we want.
I'm thinking we refactor `WithTooltip` to:
(a) use `react-popper-tooltip` behind the scenes
(b) change the API to better reflect the underlying API (e.g. `mode` => `trigger`, `startOpen` => `defaultTooltipShown`)
What do you think?
Also do you think we should publish our styled-component-ed `WithTooltip` as a package on npm?
> Experimenting with using `react-popper-tooltip` for tooltips

- src/components/screens/AddonScreen/AddonScreen.js
This addon help to change html or body attribute in stories (can help, for example, if you are using `:root` CSS variables for themes)
> Add Root Attribute addon

- site-metadata.js
- src/components/screens/AddonScreen/AddonScreen.js
Linking docs to addon-info is misleading. Setting it to Notes for now and we can update once Docs is live
> Fix docs link on addons page

- src/components/screens/AddonScreen/AddonScreen.js
Toggle the locale and directly see the result in the preview. Intl library agnostic - can be used with any intl library. Supports automatic lrt/rtl change.
> Addon storybook-addon-i18 added to list of addons

- src/components/lib/useSiteMetadata.js
This change is a result of the issue that was brought up on the storybook project by @fauverism. The link to the Notes tile on the Storybook Addons page was broken and did not lead anywhere. I identified that notes was missing from the useSiteMetadata file and thus the URL was not being pulled in. So, I added in "notes" to the officialAddons section.
Fixes https://github.com/storybooks/storybook/issues/6723
> Notes tile on Addons page now redirects to the proper link

- .storybook/webpack.config.js
- package.json
PR for https://github.com/storybooks/frontpage/issues/43
Sets `NODE_ENV` to `production` for Storybook ~npm scripts~ webpack config.
https://github.com/storybooks/frontpage/issues/43#issuecomment-493798728
> Fix Gatsby StaticQuery errors in Storybook

- src/components/screens/AddonScreen/AddonScreen.js
Shows the Storybook Design Token addon as a community addon. The addon allows for automatic generation of design token documentation from stylesheets and svg files.
https://github.com/UX-and-I/storybook-design-token
> Add storybook-design-token addon to list of community addons

- src/components/screens/AddonScreen/AddonScreen.js
Use the correct alternative text for the official Console & Links addon images.
> fix: addon alt text

- src/components/screens/AddonScreen/AddonScreen.js
This Storybook addon lets you preview your stories at a variety of breakpoints, so that you can be sure that your components will look great no matter what screen size
> Add storybook-addon-responsive-views to list of community addons

- gatsby-config.js
- package.json
- src/components/layout/Footer.js
- src/components/layout/Footer.stories.js
- src/components/layout/PageLayout.js
- src/components/layout/PageLayout.stories.js
- src/components/screens/AddonScreen/AddonScreen.js
- src/components/screens/AddonScreen/AddonScreen.stories.js
- src/components/screens/CommunityScreen/CommunityScreen.js
- src/components/screens/CommunityScreen/CommunityScreen.stories.js
- src/components/screens/IndexScreen/IndexScreen.js
- src/components/screens/IndexScreen/IndexScreen.stories.js
- src/components/screens/NotFoundScreen/NotFoundScreen.js
- src/components/screens/NotFoundScreen/NotFoundScreen.stories.js
- src/components/screens/SupportScreen/SupportScreen.js
- src/components/screens/SupportScreen/SupportScreen.stories.js
- src/components/screens/TeamScreen/TeamScreen.js
- src/components/screens/TeamScreen/TeamScreen.stories.js
- src/components/screens/UseCasesScreen/UseCasesScreen.js
- src/components/screens/UseCasesScreen/UseCasesScreen.stories.js
- yarn.lock
The Medium integration [no longer works](https://github.com/gatsbyjs/gatsby/issues/17335) as of a few days ago. This is causing our CircleCI and Netlify builds to error out without running.
In the meantime this PR removes medium so we can deploy builds and visual test again.
We'll have to find another way to add the Medium functionality back at a later point. Could definitely use help on this 🙏cc @dakebl @Keraito @lucas-carl
> Remove Medium integration so we can deploy again

- site-metadata.js
- src/components/screens/IndexScreen/IndexScreen.js
- Update version on homepage
- As of 5.2 we don't need to show the "coming soon" badge on styleguide generation section
> 5.2 frontpage update

- src/components/screens/AddonScreen/AddonScreen.js
Hey
we've created this addon for our projects at FocusReactive and want to share it with the community
https://github.com/focusreactive/storybook-addon-graphcms
>Put GraphQL queries to your stories and either see the default formatted output or pass received data to your Components. Can be connected to any GraphQL endpoint but have additional features for GraphCMS projects.
> Add Storybook Addon GraphCMS to addons Gallery

- src/components/screens/AddonScreen/AddonScreen.js
The current link (https://github.com/leoyli/addon-contexts) is to the archived repo. Switch to the new home of this addon in the official storybook repo.
> Update URL for addon-contexts

- src/components/screens/AddonScreen/AddonScreen.js
Related to the following issue https://github.com/storybookjs/storybook/issues/7052
Only the https://storybook.js.org/docs/addons/addon-gallery/ page was updated by the https://github.com/storybookjs/storybook/pull/7465 pull request
This Pull request is an update for the https://storybook.js.org/addons/ page.
> Add storybook-addon-themes to addon list

- src/components/screens/AddonScreen/AddonScreen.js
As far as I know, props combinations no longer supported.
Ref https://github.com/evgenykochetkov/react-storybook-addon-props-combinations/issues/28
That's why I created the Matrix addon as an alternative.
> Add Matrix to test addons

- gatsby-config.js
Closes https://github.com/storybookjs/storybook/issues/11484
`gatsby-plugin-netlify` was adding an `X-Frame-Options: DENY` header by default which was causing our iframed page to break inside of Storybook when trying to view the release notes. My ideal use case here is to just disable the `X-Frame-Options` header for the iframe paths, but that doesn't seem to be possible (I tried a few different ways) so I just removed that header for all pages & added back the other headers that Gatsby was adding.
I tested this in SB locally by changing the release notes iframe URL to the deploy preview URL generated here.
Ref: https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/
> Remove default Netlify headers

- src/components/screens/IndexScreen/Hero.js
This lists the total number of contributors, so it makes more sense without the plus
> Remove + from contributors

- scripts/extract-monorepo-docs.sh
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/components/screens/DocsScreen/FeatureSnippets.tsx
Goes with https://github.com/storybookjs/storybook/pull/11849
Very basic mechanism to add text entries per "feature" with a fallback to a generic "help us add this feature, here's the workaround.
@kylesuss can you take a look at the implementation. It's pretty simple right now.
@shilman can you look at the [input](https://github.com/storybookjs/storybook/pull/11849) and [output](https://deploy-preview-132--storybook-frontpage.netlify.app/docs/react/essentials/controls)? Do you think it should be an aside or something? That could be done on a per-snippet basis (inside the MDX) or always (in the component).
> Added a basic feature snippets concept

- gatsby-node.js
This code builds `versions.json`, which is what storybook's version update check requests.
This had previously.been built inside the storybook monorepo. The new code pulls over `versions/x.json` (x = `latest`/`next`) and assembles them into a single `versions.json` file on build.
> Generate versions file on build

- package.json
- src/components/screens/DocsScreen/CodeSnippets.stories.tsx
- src/components/screens/DocsScreen/CodeSnippets.tsx
- yarn.lock
I noticed that the frameworks w/ missing snippets had the messaging about the snippet being missing in the copied text! I added a slot to separate the snippet from this "pre-snippet" content so that only the snippet is copied.
> Fix copy paste issue for frameworks with missing snippets

- src/components/screens/DocsScreen/FrameworkSupportTable.tsx
so the page doesn't refresh when you click the link.
> Use GatsbyLink for framework support table header

- package.json
- src/components/layout/NpmDownloadCount.js
- yarn.lock
No idea what `react-hanger` is, but we don't need it and the `useOnMount` hook was firing all the time, hence the overuse of CPU on the homepage.
> Remove react-hanger, fix NpmDownloadCount effect

- src/components/layout/DocsLayout.js
Step 1 to get this working:
https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags
> Add docsearch meta tag for algolia to pick up

- .gitignore
- README.md
- src/components/layout/DocsLayout.js
- src/hooks/use-algolia-search.js
Search for the docs, powered by Algolia Docsearch 🎉 
Available for testing on the deploy preview:
https://deploy-preview-160--storybook-frontpage.netlify.app/docs/react/get-started/introduction
You only get results for the framework you currently have selected. I think that makes sense, but is it unclear to anyone?
> Integrate Algolia Docsearch

- src/components/layout/DocsLayout.js
You'll have to go to the deploy preview because Storybook omits the search bar.
✅ The search box now looks like this:
❌ Not this:
> Ensure search input extends the full width of available space

- src/components/screens/ReleasesScreen/IframeReleasesScreen.js
We have the "auto linked headers" in most of the frontpage (so you can click a heading & link to it), but they are not useful on the iframe screen because we don't really want people linking there.
> Hide remark header links on iframe layout

- src/components/screens/AddonScreen/AddonScreen.js
Addon is deprecated and link 404s anyway
> Remove addon-contexts from AddonScreen

- src/components/screens/AddonScreen/AddonScreen.js
The addon is deprected unless somebody takes it to maintain it.
> Delete i18n from addons page

- src/components/screens/AddonScreen/AddonScreen.js
Added storybook-addon-vscode-source to the addon list. It is a simple storybook addon that opens the source file of the component directly. In local/dev, it opens vs code and in prod deployment, it opens the file in GitHub repository.
> Add storybook-addon-vscode-source

- src/content/releases/5.0.md
- src/content/releases/5.1.md
- src/content/releases/5.2.md
- src/content/releases/5.3.md
- src/content/releases/6.0.md
- src/content/releases/6.1.md
With this pull request issue #171 is addressed and can be closed.
What was done:
- Changed the links from markdown to `<a>` tags, preventing 404 errors when the reader clicks the links.
The culprit for this issue is `gatsby-remark-link-rewrite, it works in our favor for the bulk extent of the documentation but for cases like this it will work against us, generating invalid urls, as the ones currently live in the releases page. By changing them to ´<a>´ tags, the plugin will bypass the links and will ignore them allowing them to be correct. 
Feel free to provide feedback
> Chore: Fix for issue #171

- src/components/screens/IndexScreen/Hero.js
Removes GH button from here (see right hand side). It's now present in the header on every page.
> Remove GH button from hero because it's now in the header

- src/components/layout/Header.js
I noticed that the Docs & Releases links in the nav were reloading the page. Kinda hard to keep track of all these LinkWrappers, but this should fix it for the time being.
> Add LinkWrapper for Docs, Release in nav

- static/_redirects
Discovered that this rule is leading to a lot of 404s in our SEO report. I don't think we need this anymore. It was probably redirecting addon doc pages.
> Remove addons redirect rule

- src/util/create-addons-pages.js
Issue: N/A (thanks @pocka for reporting!)
Addon details pages are linking to themselves. Fixed the query to link to NPM page
Detail page before (live site) & after (deploy preview)
> Addons: Fix link to NPM page on details page

- package.json
- src/util/absolute-links.js
- src/util/create-addons-pages.js
- yarn.lock
@shilman this at least takes you to the correct repo but, fails for most scenarios since we can't account for branch and/or release names. I'm not sure how we can get that info. 
**Update:** this is the same strategy used by NPM. It's quite hard to guess the correct url since it can be a raw user content url or reference a branch or a release.
> convert readme links to absolute

- scripts/link-monorepo-docs.sh
Re-running `yarn link-monorepo-docs` recursively deletes the developer's local edits.
I changed the script to only delete the content of `src/content/docs` if it is not a soft link.
If the softlink to `docs` already exists only the link is deleted.
> link-monorepo-docs.sh should not recursively delete if soft link already exists

- src/util/create-addons-pages.js
@shilman added a stricter check. I'm noticing that the builds do end up failing quite regularly. Even before we hit the tags request. Is there something we can do to up the back-end resources?
> fail build if tagPages in missing in response

- src/components/layout/DocsLayout.js
Netlify adds redirects for trailing slashes. Unfortunately we can't disable this. Not really an issue for us except for canonical urls. For example:
```
<link data-react-helmet="true" rel="canonical" href="https://storybook.js.org/docs/react/get-started/introduction"/>
```
The url referenced above has a 301 redirect to `https://storybook.js.org/docs/react/get-started/introduction/`. 
I added a trailing slash to canonical urls to avoid this.
> add trailing slash to canonical urls on docs pages

- gatsby-config.js
Related to the SEO issue. Add trailing slash to links in sitemap so that it's not pointing to a redirect.
> Add trailing slash to links in sitemap

- src/components/layout/addons/AddonItemDetail.js
Can't install addons with the `npx` command 😢 
I think it's correct to use the `npm` command to install the addons.
> fix typo : npx -> npm

- src/styles/formatting.js
In the latest Chrome, the `<details>` arrow has gone missing. Adding this style fixes it.
Confirm the fix by going to the deploy preview > docs > Get Started > Install and checking if the arrow is visible. [Go HERE](https://deploy-preview-241--storybook-frontpage.netlify.app/docs/react/get-started/install)
> Fix <details> arrow regression in latest Chromium

- .circleci/config.yml
- README.md
- gatsby-node.js
- package.json
- src/util/create-addons-pages.js
Added a `GATSBY_SKIP_ADDON_PAGES` flag. It's used in:
1. `yarn start:skip-addons` to allow you to run the site without having to build all addon pages
2. CircleCI to run a Gatsby build which provides data for the Storybook build which in turn is used for Chromatic. 
All in all, it should speed up the CI checks and only the netlify build should query for actual addon data. That way we aren't hammering the back-end.
> Add option to skip addon pages build for dev and when running chromatic

- src/components/screens/DocsScreen/FrameworkSupportTable.tsx
- src/util/community-addons.js
With this pull request, the framework support table component is updated to properly show the URLs related to the community addons that were moved out of the monorepo:
-design-assets
- events
- cssresources
- graphql
- queryparams
- google-analytics
- knobs 
Allowing the documentation in [here](https://storybook.js.org/docs/react/api/frameworks-feature-support) to show the correct location of said addons.
What was done:
- Created a simple module that we can build on top of for future addons that might be pushed out of the repo.
- Updated the Component to reflect the changes above.
Originally, I thought about moving this information into the Storybook docs toc.js file, but that would lead to include one additional pull request for that specific portion of information and one here to …
> Chore: Changes to the community addons

- src/components/screens/IndexScreen/Hero.js
**Why** 
Be more specific about what Storybook is actually intended for. It doesn't just help you build "bulletproof UI components" but with the entire process of building UIs with components.
> Tweak homepage headline to highlight "component driven UIs"

- src/components/layout/DocsLayout.js
1. No index the documentation for all frameworks except React
2. Index the documentation homepage for all frameworks (eg: so storybook vue” takes you to that page)
@shilman at one point we were generating the React URL as the canonical  link for all docs pages. Like so:
```
<link rel="canonical" href={`${homepageUrl}${buildPathWithFramework(slug, 'react')}/`} />
```
I think the `robots.txt` approach is cleaner since that won't tag the framework specific documentation homepage with the React canonical url.
> Optimize SEO for docs

- package.json
- yarn.lock
- Set yarn resolutions to use `"sharp": "^0.29.0"`
- To work on M1 Macs: https://sharp.pixelplumbing.com/install#apple-m1
- Gatsby themselves already did this some time ago;, but it must be in a 3+ version: https://github.com/gatsbyjs/gatsby/pull/30541
1. It works on my M1 machine locally
2. Assuming it also works on CI, can someone on a non-M1 machine please confirm that it works for you, too?
> Update sharp transitive dependency

- .storybook/useSiteMetadata.js
- gatsby-config.js
- gatsby-node.js
- site-metadata.js
- src/components/layout/DocsLayout.js
- src/components/screens/DocsScreen/FrameworkSelector.tsx
- src/components/screens/DocsScreen/VersionCTA.stories.tsx
- src/components/screens/DocsScreen/VersionCTA.tsx
- src/util/build-path-with-framework.js
- src/util/version-data.js
- Move version data out of site-metadata
- site-metadata is imported by other projects
- versions data is built from imported files that aren't present in those other projects
- Fix redirect from /docs (no trailing slash)
- Remove Gatsby redirects; use Netlify redirects
- Fix broken "View latest docs" link in VersionCTA
- Fix broken Framework selector
> Versioned docs fixes

- gatsby-node.js
- Add `/docs/<latest>/...` -> `/docs/...`
- Without this, there could be links that include the next version (e.g. `6.4`) out in the wild that would 404 once that version goes stable.
- Move `/releases` -> `/releases/<latest>` out of Gatsby and into Netlify
Here's a diff showing the generated output in the `/public/_redirects` file.
```diff
/docs /docs/react/get-started/introduction 301
/docs/react /docs/react/get-started/introduction 301
/docs/vue /docs/vue/get-started/introduction 301
/docs/angular /docs/angular/get-started/introduction 301
/docs/web-components /docs/web-components/get-started/introduction 301
/docs/ember /docs/ember/get-started/introduction 301
/docs/html /docs/html/get-started/introduction 301
/docs/mithril /docs/mithril/get-started/introduction 301
/docs/marko …
```
> Fix redirects

- gatsby-browser.js
- gatsby-ssr.js
Emotion comes with 0-config SSR - by default one doesn't have to configure it anyhow, integrate with it etc. However, it comes with a price - some selectors might not work properly. The problem is that to achieve that we render `<style/>` elements "inline" and we move them to `<head/>` on the client-side.
So for example something like this might accidentally target such "inline" `<style/>`:
https://github.com/storybookjs/frontpage/blob/f92ce565a8bcab80845a374e5cf873519bbd7d39/src/components/layout/DocsLayout.js#L81
This gets fixed when the element gets moved to `<head/>` but it leaves the site with an ugly SSR blink, like the reported one, before client-side JS kicks in.
This particular problem could probably be fixed with something like this:
<details>
<summary>git diff</summary>
```diff …
```
> Setup explicit, manual, SSR for Emotion

- gatsby-node.js
- All redirects to release branches now use `200` code, ensuring they proxy correctly, masking the destination URL
> Fix docs redirects

- src/util/redirects-raw.txt
- static/_redirects
- Redirect /docs/<framework>/get-started/examples to /showcase
- Ensure /design-system always points to latest Chromatic build
> Add /showcase proxy rewrite

- gatsby-config.js
- gatsby-node.js
- scripts/extract-monorepo-version.sh
- src/util/versions.js
- static/_redirects
- Extract `docs/toc.js` from each docs version
- Use those TOCs to generate a sitemap that only includes pages that are present within each version
-----
You can see the generated file here: https://deploy-preview-344--storybook-frontpage.netlify.app/sitemap-all.xml
Note the pages it contains, for a slug like `/sharing/publish-storybook`, which is present in the "latest" and "next" TOC, but not any others (at the moment):
- ✅  https://storybook.js.org/docs/react/sharing/publish-storybook
- ✅  https://storybook.js.org/docs/6.5/react/sharing/publish-storybook
- ❌  https://storybook.js.org/docs/6.3/react/sharing/publish-storybook
- ❌  https://storybook.js.org/docs/7.0/react/sharing/publish-storybook
> Update generated `sitemap-all.xml`

- src/components/screens/IndexScreen/IndexScreen.js
Minor one line change to revert previous styling tweak for BlogCTA spacing on desktop.
> Remove extra spacing from top of BlogCTA on desktop

- src/components/layout/addons/AddonItem.js
- Fix AddonItem component word-break.
- Before: 
- After:
> Fix word-break

- gatsby-config.js
- gatsby-node.js
- static/robots.txt
- Included other sitemaps:
- [/showcase/sitemap-0.xml](https://storybook.js.org/showcase/sitemap-0.xml)
- [/tutorials/sitemap.xml](https://storybook.js.org/tutorials/sitemap.xml)
- Blog sitemaps are temporarily excluded
- The original sitemaps are incorrect (missing `/blog/` directory)
- https://storybook.js.org/blog/sitemap-pages.xml
- https://storybook.js.org/blog/sitemap-posts.xml
- https://storybook.js.org/blog/sitemap-tags.xml
- I'm also not sure we _want_ to include all of those (e.g. probably not the `pages` one?)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>https://storybook.js.org/sitemap/sitemap-0.xml</loc>
</sitemap>
</sitemapindex>
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex …
```
> Copy other sitemaps into /public & update index

- gatsby-node.js
- src/components/layout/DocsLayout.js
- src/util/redirects-raw.txt
- Only include canonical URLs for "latest" doc pages
- Versioned pages may have a `slug` that no longer exists, leading to a 404
- Versioned pages are noIndex'd, so there's no SEO penalty
- Update redirects
> Seo updates

- gatsby-node.js
- Wrap each `<loc>` in `<sitemap>`
Per https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps, the format of the sitemap index file has been incorrect since #373.
```xml
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>https://storybook.js.org/sitemap/sitemap-0.xml</loc>
<loc>https://storybook.js.org/sitemap/blog/sitemap.xml</loc>
<loc>https://storybook.js.org/sitemap/showcase/sitemap-0.xml</loc>
<loc>https://storybook.js.org/sitemap/tutorials/sitemap.xml</loc>
</sitemap>
</sitemapindex>
```
```xml
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>https://deploy-preview-378--storybook-frontpage.netlify.app/sitemap/sitemap-0.xml</loc>
</sitemap>
<sitemap> …
```
> Fix sitemap index

- src/components/layout/Community.js
- src/components/screens/CommunityScreen/CommunitySectionHeader.stories.tsx
Technique from this blog post https://pqina.nl/blog/fix-html-video-autoplay-not-working/
Autoplay can be finicky. These videos weren't autoplaying reliably. Sometimes they were and sometimes they weren't. I added the `muted` prop to match Chrome and Safari's best practices.
How to test: 
1. Go to the published Storybook and search for the CommunityScreen`../screens-communityscreen--default`
2. Check that the videos are autoplaying
> Added muted property

- gatsby-node.js
- Correct location of blog & tutorials sitemaps
- The updates to Gatsby 4 caused the generated sitemaps to now use an index format
- New sitemaps for each:
- https://storybook.js.org/blog/sitemap/sitemap-0.xml
- https://storybook.js.org/tutorials/sitemap/sitemap-0.xml 
- Refactor to handle nested sitemap locations
- `blog/sitemap.xml` vs. `blog/sitemap/sitemap-0.xml`
The generated index ([preview here](https://deploy-preview-402--storybook-frontpage.netlify.app/sitemap/sitemap-index.xml)) now looks like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap><loc>https://storybook.js.org/sitemap/sitemap-0.xml</loc></sitemap>
<sitemap><loc>https://storybook.js.org/sitemap/blog/sitemap.xml</loc></sitemap> …
```
> Fix sitemap index generation

- src/components/screens/IndexScreen/Develop.js
This URL takes you to the middle of the `/why` page which feels like a bug. I removed the jump link so clicking on the URL takes you to the top of the page.
> Remove jump link from `/why` urls on homepage

- src/styles/formatting.js
**Why**
When you click on an anchor link or a `detail`, there is no visual indicator of where you are and what you're supposed to look at. That's confusing when theres a text wall of docs. 
**What**
Added `:target` styles to highlight when anchor links are used. In practice, this means whenever we link to a specific heading or `detail` via a `...#cool-heading` it'll be obvious what the user is supposed to look at.
> Highlight anchor links to make them easier to discern

- src/components/screens/DocsScreen/YouTubeCallout.tsx
Add border to YouTubeCallout to improve acuity.
Before: 
After:
> Add border to youtube callout

- src/components/screens/DocsScreen/FeatureSnippets.tsx
The current `.split(-)` code has side effects on dashed framework names like **web-components**.
The `.split(-)` part is removed from the codebase.
closes #228
> fix: remove the path splitting due to web-components

- src/components/screens/DocsScreen/CodeSnippets.stories.tsx
- src/components/screens/DocsScreen/CodeSnippets.tsx
See corresponding `storybook` PR: https://github.com/storybookjs/storybook/pull/20053
**Preview:**
> **Note**: This API (specifically, the `csf2Path` prop) was chosen to allow pointing to different pages for some snippets in the future. While it is unused today (all CSF 2 snippets live on the same page as their CSF 3 versions), that may not be true in the future.
If you'd like to see the message in the actual docs, you'll have to run it locally, as the deploy preview is built from the "latest" docs, which do not have the necessary attributes on the CodeSnippets in the docs content.
1. Check out this branch, `kylegach/dx-392-build-csf-2--csf-3-snippet-banner`
1. Run `yarn extract-monorepo-docs add-csf-2-to-3-banner`
1. Run `GATSBY_SKIP_ADDON_PAGES=true yarn start`
That will pull down the …
> Add CSF message to CodeSnippets

- src/components/layout/DocsLayout.js
- src/components/layout/integrations/IntegrationsLayout.js
- src/components/screens/CommunityScreen/CommunitySidebar.tsx
- src/components/screens/DocsScreen/VersionCTA.tsx
Table of Contents: Added more generous spacing between emoji and text to improve readability
VersionCTA: adjust spacing to match the YoutubeCallout
> Tweak styling: Table of contents, VersionCTA

- src/components/screens/DocsScreen/FrameworkSupportTable.tsx
With this small pull request, a minor change is implemented to address a 404 with the addons listed in the API section of the official docs resulting from the recent monorepo changes in terms of structuring.
What was done:
- Updated the string to feature in the `code` folder
In the long run, we'll need to start thinking of a better way to address this.
@valentinpalkovic I've added you as a reviewer so that you can get a familiar sense of where the information is pulled in here. I'm going to update the Storybook monorepo and loop you in so that you get the full scope of the required changes.
> Chore: Prevents 404 with addons

- static/_redirects
it was supposed to be `/status/:splat` rather than `/:splat`
> Fix status page redirect

- netlify.toml
We recently added CSF headers across various Storybook sites and it broke embedding, and it’s showing up on the documentation page on [storybook.js.org](http://storybook.js.org/) on how to embed stories:
https://storybook.js.org/docs/react/sharing/embed
As recommended by Tom and Jarel, we need to add `*.chromatic.com` to the `frame-src` to resolve the issue.
> Fix a CSF header issue that is breaking embeds

- src/content/recipes/@emotion/styled.md
- src/content/recipes/styled-components.md
**What I did:**
1. Fix typos 
2. Use the spelling of styled-components they use – else we don't get any SEO benefits
3. Add instructions for `GlobalStyle` 
**Why add instructions for `GlobalStyle`?** 
Most apps have globally-scoped CSS, even CSS-in-JS. This is a key part of Storybook's onboarding process that users with existing apps must do to setup successfully. We should document how to apply `GlobalStyle` in Storybook to address this common task.
@kylegach can I get your review on the instructions in styled-components.md? Once you give the green light, I'll apply that to Emotion as well.
> Recipe edits for styled-components and Emotion

- src/components/screens/DocsScreen/CodeSnippets.tsx
- No longer show `common` snippets if non-`common` snippets are available
For this URL, `/docs/web-components/writing-stories/play-function/`, and this instance:
```jsx
<CodeSnippets
paths={[
'common/register-component-with-play-function.js.mdx',
'common/register-component-with-play-function.ts.mdx',
'web-components/register-component-with-play-function.js.mdx',
'web-components/register-component-with-play-function.ts.mdx',
]}
/>
```
-----
URLs like `/docs/react/writing-stories/play-function/` (i.e. if an exact framework match is unavailable) display the `common` snippets as they did before:
-----
The case where a framework has a match in one language and not another also displays as before. Here, the `react` framework does not match for the `JS` language, so it falls back to `common`. …
> Update CodeSnippets logic

- gatsby-config.js
- src/components/layout/DocsLayout.js
- src/components/layout/integrations/recipes/RecipeItemDetail.js
- src/components/screens/DocsScreen/DocsSearch.tsx
- src/components/screens/IntegrationsCatalog/RecipesDetailScreen/RecipesDetailScreen.js
We want to add recipes into the global search which requires some markup changes for Algolia to index them.
- Use h1 tag for recipe header title
- Remove unused loading state from recipeItemDetail
- Add "Docs > " to hidden algolia indexing title on docs layout
- Change name of directory for sitemap-all
> Update recipe and doc layouts for global search indexing

- src/components/layout/DocsLayout.js
- src/components/layout/PageLayout.js
- src/constants/global-search.js
Used to tweak cases where recipes are coming up higher than docs when search the name of a framework
The docusearch docs suggest using an integer here so that you can use their sort methods
> Add importance meta to rate docs higher than recipes

- src/content/recipes/vuetify.md
Wrap stories in `v-app` so storybook can render layout components from vuetify like `v-app-bar`
Addresses #488 
[Recipe preview](https://deploy-preview-489--storybook-frontpage.netlify.app/recipes/vuetify/)
> [Fix] vuetify recipe: Wrap stories in v-app

- src/styles/formatting.js
Content styling tweaks to go along with [new API reference pages](https://github.com/storybookjs/storybook/pull/21113).
- ~Add styles for `<h5>`~
- `<code>` inherits color from parent `<a>`
> Minor styling tweaks

- gatsby-config.js
- gatsby-node.js
- site-metadata.js
- src/components/layout/DocsLayout.js
- src/components/layout/DocsLayout.stories.js
- src/components/layout/PageLayout.js
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/components/screens/DocsScreen/FrameworkSelector.stories.tsx
- src/components/screens/DocsScreen/VersionCTA.stories.tsx
- src/components/screens/DocsScreen/VersionSelector.stories.tsx
- src/components/screens/IndexScreen/Develop.js
- src/constants/global-search.js
- src/util/redirects-raw.txt
- static/_redirects
- Update redirects
Old:
- `/docs` → `/docs/react/get-started/introduction`
- `/docs/<version>` → `/docs/<version>/react/get-started/introduction`
- `/docs/<version>/<framework>` → `/docs/<version>/<framework>/get-started/introduction`
New:
- `/docs` → `/docs/react/get-started/install`
- `/docs/<version>` → `/docs/<version>/react/get-started/install`
- `/docs/<version>/<framework>` → `/docs/<version>/<framework>/get-started/install`
- Store `/docs/get-started/install` slug in site-metadata
- Make install docs page always searchable
- Search is faceted on the current framework
- This change ensures that each framework's install docs page is searchable, regardless of current framework
- Update misc stories
- To use `/docs/get-started/install` instead of `/docs/get-started/introduction`
- Add …
> Update various redirects from intro -> install

- src/components/screens/DocsScreen/CodeSnippets.tsx
- src/components/screens/DocsScreen/DocsScreen.tsx
Prior to this change, links to a heading's anchor would often "miss", due to the dynamic snippet loading. This change checks for all snippets to load, then imperatively scrolls to the desired element.
1. Open this page of the deploy preview
- https://deploy-preview-503--storybook-frontpage.netlify.app/docs/react/writing-stories/args#mapping-to-complex-arg-values
2. Confirm that the page doesn't jump around as it loads
- i.e. That the highlighted target heading stays near the top of viewport
> Fix docs anchor links

- netlify.toml
Fixes: https://github.com/storybookjs/storybook/issues/21324
Related: https://github.com/storybookjs/frontpage/pull/508
The last PR didn't fix the iFrame issue. I forgot to maintain the order of the headers config resulting in "/*" overriding the previous headers config.
Also removed obsolete X-Frame-Options and used "frame-ancestors 'self';" instead.
REF: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#:~:text=This%20is%20an-,obsolete%20directive,-that%20no%20lonZger
> re-tested & fixed headers for release page

- gatsby-node.js
- src/components/screens/DocsScreen/VersionSelector.tsx
- Fix `/docs/next/...` redirect - If "next" version is available, redirect to that - Otherwise, redirect to "latest" version
- Don't render "Prerelease" section of VersionSelector menu if empty
> Allow no "next" docs

- src/content/recipes/@mui/material.md
With this small pull request the deprecated reference to `.stories.mdx` is removed from the material ui recipe as we're no longer documenting usage in our documentation nor providing it as a configuration option.
@Integrayshaun, if you're ok with it, merge this after 7.0 lands as to avoid confusion. 
Thanks in advance
> Chore: (Recipes) Removes deprecate reference to stories.mdx

- src/components/layout/DocsLayout.js
- static/_redirects
Reverts changes in #485 & #493 
- Remove survey CTA from docs sidebar
- Remove `/survey` redirect
> Remove survey

- src/components/screens/DocsScreen/CodeSnippets.tsx
Add missing apostrophe in `MissingFrameworkMessage`.
> Fix typo on MissingFrameworkMessage

- src/components/screens/DocsScreen/CodeSnippets.tsx
Add missing apostrophe in `MissingCodeLanguageMessage`. Sorry for the nit-picky PRs!
> Fix typo on MissingCodeLanguageMessage

- netlify.toml
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/components/screens/DocsScreen/Feedback.stories.tsx
- src/components/screens/DocsScreen/Feedback.tsx
- src/functions/docs-feedback.js
Closes #537 
- Add Feedback component
- Add Feedback to DocsScreen
- Add docs-feedback cloud function
- Creates/updates discussion on Storybook repo
- Tracks cumulative rating
- Re-opens closed discussions with new comments
- Attempt to reduce spam with honeypot and IP rate limiting
> ⚠️ Important note: Even though this is a preview, it is writing to the main Storybook monorepo. So please be careful what you say if you submit a comment and either delete your discussion when you're done or ping me to do it for you.
> Add docs feedback widget

- src/components/screens/DocsScreen/CodeSnippets.test.ts
If I understood correctly the comments left by @kylegach, tests were meant to not be skipped once v7 was tagged as latest.
Tests all passed when I checked.
> Remove skip on v7 tests for CodeSnippets

- src/content/recipes/tailwindcss.md
You need to configure the add-on for this to work and this instruction to skip the step is quite misleading and confusing.
> chore: remove misleading instruction related to v7

- .circleci/config.yml
- src/util/custom-events.test.ts
- src/util/custom-events.ts
- Remove negative lookbehind regex pattern, which isn't supported in older Safari
> Fix snippetType in tracking

- .gitignore
- gatsby-node.js
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/components/screens/DocsScreen/Feedback.tsx
- src/functions/docs-feedback.js
> **Note**: I suggest reviewing [commit-by-commit](https://github.com/storybookjs/frontpage/pull/552/commits). The changes were carefully structured to aid review.
This is an effort to harden the docs feedback widget against scammers and other bad actors _without_ going all the way to requiring users to authenticate first.
- Generate docs-metadata file on build
- Update docs-feedback to use `slug` instead of `path`
- Easier than removing the version (sometimes) and framework from the path
- Allows for direct comparison with docs slugs
- Validate submitted data against allowed values
- Check slug, version, framework, and rating
- Validate against a tricky header on the request
- Based on [Netlify's guidance](https://answers.netlify.com/t/support-guide-how-to-apply-access-control-for-netlify …
> Validate docs feedback

- src/util/relative-to-root-links.js
- src/util/relative-to-root-links.test.ts
This approach will eventually[^1] replace `LinkWithVersion`. It allows for functional links when viewing on GitHub.
- `../../../release-6-5/docs/api/csf.md` → `/docs/6.5/react/api/csf.md`
- Add tests
[^1]: For now, `LinkWithVersion` remains available in MDX, so that I can update the actual docs content in the monorepo. After that, I'll remove that component, as it is no longer necessary.
> Handle versioned links in relative-to-root-links

- static/_redirects
From the [commit](https://github.com/storybookjs/frontpage/commit/05e5d32e9c38c87403d1185d9178016daf3b3098) which added the version to the URL:
> Redirect to v6.5 for telemetry docs
>    - Temporarily, until 6.5 goes stable
Whoops. 😅
> Remove version from telemetry redirect

- src/util/relative-to-root-links.js
- src/util/relative-to-root-links.test.ts
Re-doing the already-approved-and-merged https://github.com/storybookjs/frontpage/pull/558, due to a GitHub hiccup causing it to not actually be merged.
> Remove `.md` extension on docs links

- src/components/screens/DocsScreen/DocsScreen.tsx
- src/util/relative-to-root-links.js
- No longer used, per https://github.com/storybookjs/frontpage/pull/555 & https://github.com/storybookjs/storybook/pull/22966
- Simplify `relativeToRootLinks`
> Remove LinkWithVersion

- src/content/recipes/@emotion/styled.md
- src/content/recipes/@mui/material.md
- src/content/recipes/styled-components.md
- src/content/recipes/tailwindcss.md
Include instructions on how to run the codemod for `@storybook/addon-styling` in recipes of the tools supported.
> Update recipes to include codemod instructions

- src/styles/formatting.js
Closes #560 by removing opinionated styling rules that do not match GitHub's markdown styling
> Remove auto image center

- package.json
- scripts/append-package-tags-in-snippets.js
- scripts/append-package-tags-in-snippets.test.ts
- src/util/version-data.js
Closes #532 
See tests for behavior details.
I also made a [demo PR](https://github.com/storybookjs/frontpage/pull/574), to provide a [diff of how the snippets will be changed](https://github.com/storybookjs/frontpage/pull/574/commits/df23a3b0f5bf4b22be746db3b2573e4ee6cbf72e) (when docs are preRelease).
````md
```sh
npx storybook init
```
```sh
npx storybook@next upgrade --prerelease
```
```sh
yarn add -D @storybook/testing-library @storybook/jest @storybook/addon-interactions
```
`npx storybook init`
`@storybook/testing-library`
````
````md
```sh
npx storybook@latest init
```
```sh
npx storybook@next upgrade --prerelease
```
```sh
yarn add -D @storybook/testing-library @storybook/jest @storybook/addon-interactions
```
`npx storybook@latest init`
`@storybook/testing-library`
````
````md …
```
> Append version tag to matched packages in snippets

- src/content/recipes/@emotion/styled.md
- src/content/recipes/@mui/material.md
- src/content/recipes/styled-components.md
- src/content/recipes/tailwindcss.md
- Add warning to run codemod from a clean working tree
- Draw more attention to when you should avoid using the webpack configuration options in addon-styling
> Update recipes to add warning about codemod use

- src/components/screens/IndexScreen/Integrations.js
- src/components/screens/IndexScreen/Share/Share.js
- src/components/screens/IndexScreen/Test.js
- src/util/redirects-raw.txt
This pull request follows up on the Storybook documentation pull request [here](https://github.com/storybookjs/storybook/pull/22897) that introduces some structural changes to the documentation organization and outlines the current state of the testing library support.
What was done:
- Updated the redirects
- Updated some misc links across the website to prevent a 404 situation or add yet another redirect to the growing list of them
@kylegach, when you have a moment, can you take a look and follow up with me so that we can merge this one after the already-mentioned documentation pull request is merged?
> Chore: Updates redirects and links to prevent 404s

- src/components/screens/DocsScreen/YouTubeCallout.stories.tsx
- src/components/screens/DocsScreen/YouTubeCallout.tsx
With this pull request the YoutubeCallout component was expanded to feature a `params` option, giving us the option to link specific timestamps based on the underlying library used (i.e., `react-lite-youtube-embed`)
What was done:
- Updated the component
- Added example stories to test the implementation
If nothing arises, this should be merged ahead of the following documentation [pull request](https://github.com/storybookjs/storybook/pull/23797) to avoid issues.
@kylegach, when you have a moment, take a look and let me know of any feedback.
Appreciate it 🙏
> UI: Add params config to YoutubeCallout component

- src/styles/formatting.js
Necessary for complex API references, e.g. `main-config-indexers`:
`IndexerOptions` is an H4; `makeTitle` is an H5.
> Add styles for H5 level headings

- src/components/screens/IntegrationsCatalog/IntegrationsCatalogHomeScreen/IntegrationsCatalogHomeScreen.js
- src/components/screens/IntegrationsCatalog/IntegrationsCatalogHomeScreen/IntegrationsCatalogHomeScreen.stories.js
- src/util/create-integrations-pages/create-integrations-home-page.js
Trending is currently filled with addons that are out of date and unmaintained.
We should hide them for now until we can curate our own list
> Remove trending from catalog homepage

- gatsby-config.js
- gatsby-node.js
- src/components/screens/DocsScreen/VersionSelector.stories.tsx
- src/components/screens/DocsScreen/VersionSelector.tsx
- src/components/screens/ReleasesScreen/ReleasesScreen.js
- src/components/screens/ReleasesScreen/ReleasesScreen.stories.js
- src/content/releases/8.0.md
- For now, the v8 docs are only going to be published to provide permalinks. We don't want to expose the option in the menu.
> Hide v8 from VersionSelector menu

- src/components/screens/CommunityScreen/CommunitySupport.tsx
- src/components/screens/IndexScreen/SocialValidation.js
**Note**: In the `CommunitySupport` component, I added a direct link to GH Discussions, _rather_ than editing the `ChatUrl` prop. That's because `ChatUrl` goes to Discord everywhere (I think?) and there are many places where we'll still want to keep the Discord link as it is.
> Add GitHub Discussion links

- gatsby-config.js
- gatsby-node.js
- src/components/screens/DocsScreen/VersionSelector.stories.tsx
- src/components/screens/DocsScreen/VersionSelector.tsx
- src/components/screens/ReleasesScreen/ReleasesScreen.js
- src/components/screens/ReleasesScreen/ReleasesScreen.stories.js
- src/content/releases/8.0.md
Until the [version on `release-8-0` starts with `8.0.0`](https://github.com/storybookjs/storybook/pull/24711), this will not work correctly.
> Revert #603 "Hide v8 from VersionSelector menu"

- src/components/basics/Pill.stories.tsx
- src/components/basics/Pill.tsx
- src/components/screens/DocsScreen/DocsContext.tsx
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/components/screens/DocsScreen/RendererSelector.stories.tsx
- src/components/screens/DocsScreen/RendererSelector.tsx
1. Open [the deploy preview](https://deploy-preview-624--storybook-frontpage.netlify.app/docs/writing-stories/decorators)
1. Confirm that the pills + menu look and feel correct
1. Confirm that it is highlighting the correct renderer
1. Confirm that you can choose another _core_ renderer (React, Vue, Angular, Web Components)
1. Confirm that you can choose a _community_ renderer (under the More menu)
1. Confirm that your selected community renderer has taken the place of the last pill (Web Components)
1. Confirm that the last pill is now first in the More menu
1. Confirm that your selected community renderer is not in the menu
1. Confirm that you can select a _core_ renderer when a _community_ renderer is highlighted
1. Confirm that all of the pill + menu manipulation from the previous step …
> Refactor RendererSelector to pill-based design

- src/components/basics/InPageTOC.stories.tsx
- src/components/basics/InPageTOC.tsx
- src/components/layout/DocsLayout.tsx
- src/components/screens/DocsScreen/DocsScreen.stories.tsx
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/components/screens/DocsScreen/RendererSelector.tsx
- src/components/screens/DocsScreen/YouTubeCallout.tsx
- src/styles/formatting.js
- Fix non-fluid DocsLayout
- Fix scroll margin of headings and code snippets
- Ensure `code` in content doesn't overflow column
- Remove drop shadow on YouTubeCallout
- Add "On this page" TOC
- Add InPageTOC component
- Query `tableOfContents` in DocsScreen
- Add right rail to DocsScreen when wide enough to accommodate it
> [!NOTE]
> Currently, this has to be _quite_ wide (1548px) for the main content to be wide enough to be legible. (The screenshot was taken at 1800px wide.) We need to discuss the overall page layout to improve this. [See related code comment.](https://github.com/storybookjs/frontpage/pull/628/files#diff-56237f547a4dc2c2c48b375dea50d79c8b7e20556b67152c6e7158c2b97c8567R34-R46).
> [!NOTE]
> The broken sidebar links are a [known, unrelated …
> Add "On this page" TOC

- src/components/layout/DocsLayout/Sidebar.tsx
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/content/releases/7.5.md
- src/styles/formatting.js
- src/util/add-state-to-toc.js
- src/util/relative-to-root-links.js
- src/util/relative-to-root-links.test.ts
- Handle headings that redirect to another path
- Add support for `hideRendererSelector` in frontmatter
- Ensure `index.md` pages still work with "Edit on GitHub" links and `relative-to-root-links`
- Simplify markdown table styling
> Various TOC improvements

- src/content/releases/7.6.md
- src/util/redirects-raw.txt
- static/_redirects
> [!WARNING]
> This should only be merged after Storybook `7.6` is released.
This will also almost certainly have merge conflicts with https://github.com/storybookjs/frontpage/pull/626, which is likely to be merged prior to this one. I (Kyle) will deal with that.
> Updates for Storybook `7.6`

- package.json
- src/components/basics/CodeSnippets/BaseCodeSnippet/BaseCodeSnippet.tsx
- src/components/basics/CodeSnippets/SyntaxHighlighterContext.tsx
- src/components/basics/CodeSnippets/utils/parse-snippet-content.utils.ts
- src/components/basics/Pre.tsx
- src/components/screens/DocsScreen/CodeSnippets/CodeSnippets.tsx
- src/components/screens/DocsScreen/CodeSnippets/fetch-snippets.utils.tsx
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/styles/formatting.js
- yarn.lock
- Add `@types/react`
- Apply `id` attribute to CodeSnippets and Pres
- So that https://github.com/storybookjs/frontpage/pull/503 can do its thing
- Reduce font-size of code blocks
- Ensure not-found ts-4-9 snippets fall back to ts
- Parse MDX comments into snippet titles
- Fix type errors
<table>
<tr>
<td>
Here, TS 4.9 was selected, causing the snippet to disappear entirely
</td>
<td>
Note the first empty snippet and the `{` & `}` wrapping the titles
</td>
</tr>
</table>
<table>
<tr>
<td>
Note that TS 4.9 is selected and the snippet still renders the TS version
</td>
<td>
Note that the one-line snippet displays properly and the titles are correct
</td>
</tr>
</table>
> Snippet fixes

- gatsby-node.js
- site-metadata.js
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/components/screens/IndexScreen/Develop.js
- src/components/screens/IndexScreen/Document.js
- src/components/screens/IndexScreen/Test.js
- src/components/screens/IntegrationsCatalog/AddonsDetailScreen/AddonsDetailScreen.js
- src/content/recipes/@emotion/styled.md
- src/content/recipes/bootstrap.md
- src/content/recipes/styled-components.md
- src/content/recipes/tailwindcss.md
- src/content/recipes/vuetify.md
- src/util/generateRedirects/generateRedirects.js
- src/util/generateRedirects/generateRedirects.test.ts
- src/util/redirects-raw.txt
- static/_redirects
- Fix FrameworkSupportTable
- Fix broken renderer icons in AddonsDetailScreen
- Remove renderer from various static URLs
- Also remove `/introduction` and `/overview`
- Update generated redirects to respect versions
- `redirects-raw` is now broken up by version the redirect was added
- Generated redirects include version and possibly renderer, as appropriate for the version
> Various fixes, inc. FrameworkSupportTable, broken images, and versioned generated redirects

- src/util/generateRedirects/generateRedirects.js
- src/util/generateRedirects/generateRedirects.test.ts
- Furthering #641 
- See snapshot diff
> Fix generated redirects

- src/components/screens/DocsScreen/CodeSnippets/fetch-snippets.utils.tsx
This fix effectively stitches together a snippet that contains multiple code blocks, like this:
````mdx
```js
// Button.stories.js
import Button from './Button.svelte';
import MarginDecorator from './MarginDecorator.svelte';
export default {
component: Button,
decorators: [() => MarginDecorator],
};
// Your stories here.
// Don't forget to use the component you're testing and not the MarginDecorator component
```
```html
<div>
<slot />
</div>
<style>
div {
margin: 3em;
}
</style>
```
````
Into a unified code block, using the language of the first one:
````mdx
```js
// Button.stories.js
import Button from './Button.svelte';
import MarginDecorator from './MarginDecorator.svelte';
export default {
component: Button,
decorators: [() => MarginDecorator],
};
// Your stories here.
// Don't …
> Handle snippets with multiple code blocks

- static/_redirects
The blog requires a slightly different redirect because the `/api` endpoint is already used for something else.
> add another redirect for plausible (blog specific)

- scripts/append-package-tags-in-snippets.js
- scripts/append-package-tags-in-snippets.test.ts
- Unlike `add` it should _not_ append tags to the removed packages
Follow up to #657 
You will _not_ be able to test the pre-release behavior in the deploy preview (only the latest version of the docs are deployed for that).
Instead, you must verify the test suite is correct and comprehensive.
> Update package tags script to handle `remove`

- src/components/screens/DocsScreen/CodeSnippets/CodeSnippets.tsx
- src/components/screens/DocsScreen/CodeSnippets/fetch-snippets.utils.tsx
- src/components/screens/DocsScreen/CodeSnippets/fetch-snippets.utilts.test.ts
- Coerce `native-format` type to `html` syntax
- Ensure they always match the current code language - Thus, it renders as a snippet tab alongside the JS/TS snippet tab
- Further prettify the tab names
```
Uncaught Error: No language registration for native-format
```
> Fix svelte native-format snippets

- gatsby-config.js
- gatsby-node.js
- site-metadata.js
- src/components/screens/DocsScreen/DocsScreen.tsx
- src/components/screens/IndexScreen/Develop.js
- src/util/generateRedirects/generateRedirects.test.ts
- static/_redirects
Per https://github.com/storybookjs/storybook/pull/26401
- Place version data directly in site-metadata
- No longer update install guide title
- Update redirects
> Update "install page" to `/docs/get-started`

- src/content/releases/8.0.md
> Update URL to 8.0 migration guide

- src/util/relative-to-root-links.js
- src/util/relative-to-root-links.test.ts
- Useful for preserving links to prior headings
> Add support for named anchors
